name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: AzizMtg # Replace AzizMtg with your GitHub username
          svg_out_path: snake.svg
          svg_rect_width: 800
          svg_rect_height: 400
          svg_fill_color: "rgba(0,0,0,0)"
          svg_stroke_color: "rgba(0,0,0,0)"
          svg_stroke_width: 1

      - name: push snake.svg to the output branch
        uses: EndBug/add-and-commit@v7
        with:
          add: "snake.svg"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add snake.svg"
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
